"""adding filename attr do data table

Revision ID: 012ca424b0a1
Revises: 31bf59f99fc3
Create Date: 2022-06-18 18:17:27.675708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012ca424b0a1'
down_revision = '31bf59f99fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('file_name', sa.String(), nullable=True))
    op.drop_index('ix_data_speicher_oid', table_name='data')
    op.create_index(op.f('ix_data_file_name'), 'data', ['file_name'], unique=False)
    op.drop_column('data', 'speicher_oid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('speicher_oid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_data_file_name'), table_name='data')
    op.create_index('ix_data_speicher_oid', 'data', ['speicher_oid'], unique=False)
    op.drop_column('data', 'file_name')
    # ### end Alembic commands ###
