"""Add coloumn has ovted

Revision ID: 02be9346f872
Revises: 3045cc489b74
Create Date: 2022-05-28 07:33:20.963673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02be9346f872'
down_revision = '3045cc489b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_voted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_voted')
    # ### end Alembic commands ###
