"""fixing to with data project model

Revision ID: 2ebe8bb0b5ce
Revises: b4dbeaef9eb6
Create Date: 2022-06-10 13:42:17.305000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebe8bb0b5ce'
down_revision = 'b4dbeaef9eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
