"""Add column Teacher  User

Revision ID: 3045cc489b74
Revises: dd2e37d8b2e6
Create Date: 2022-05-26 14:47:33.982273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3045cc489b74'
down_revision = 'dd2e37d8b2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_teacher')
    # ### end Alembic commands ###
