"""removing uneeded teacher columbs 

Revision ID: 31bf59f99fc3
Revises: a55c9fdce08a
Create Date: 2022-06-13 19:47:02.435878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bf59f99fc3'
down_revision = 'a55c9fdce08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_description', table_name='teacher')
    op.drop_index('ix_teacher_title', table_name='teacher')
    op.drop_column('teacher', 'description')
    op.drop_column('teacher', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teacher', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_teacher_title', 'teacher', ['title'], unique=False)
    op.create_index('ix_teacher_description', 'teacher', ['description'], unique=False)
    # ### end Alembic commands ###
