"""Models Project and school added

Revision ID: 6d9b7ff28595
Revises: d4867f3a4c0a
Create Date: 2022-05-25 12:38:09.376482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9b7ff28595'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_id'), 'school', ['id'], unique=False)
    op.create_index(op.f('ix_school_school_name'), 'school', ['school_name'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('links', sa.String(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('vote_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=False)
    op.create_index(op.f('ix_project_group_name'), 'project', ['group_name'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_project_links'), 'project', ['links'], unique=False)
    op.create_index(op.f('ix_project_project_name'), 'project', ['project_name'], unique=False)
    op.create_index(op.f('ix_project_vote_counter'), 'project', ['vote_counter'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_project_vote_counter'), table_name='project')
    op.drop_index(op.f('ix_project_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_links'), table_name='project')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_group_name'), table_name='project')
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_school_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_id'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
