"""removing uneeded teacher columbs 

Revision ID: a55c9fdce08a
Revises: 2ebe8bb0b5ce
Create Date: 2022-06-13 19:45:03.658564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55c9fdce08a'
down_revision = '2ebe8bb0b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
