"""add owner id to project model

Revision ID: aa01946d67d2
Revises: 02be9346f872
Create Date: 2022-06-10 13:21:24.578498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa01946d67d2'
down_revision = '02be9346f872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'owner_id')
    # ### end Alembic commands ###
