"""fixing to with data project model

Revision ID: b4dbeaef9eb6
Revises: d8f4dac7a5b8
Create Date: 2022-06-10 13:28:02.798852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4dbeaef9eb6'
down_revision = 'd8f4dac7a5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
