"""fixing to with data project model

Revision ID: d8f4dac7a5b8
Revises: aa01946d67d2
Create Date: 2022-06-10 13:25:18.531217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f4dac7a5b8'
down_revision = 'aa01946d67d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
