default_context:
  project_name: 'webapp'
  project_slug: 'webapp'
  domain_main: 'localhost'
  domain_staging: 'stag.localhost'
  docker_swarm_stack_name_main: 'localhost'
  docker_swarm_stack_name_staging: 'stag-localhost'
  secret_key: '000b1d3d11f164fbe259d11b5ce108fe733ac9d615134b85c7d429c9ed455d9f'
  first_superuser: 'artiom.blinovas@gmail.com'
  first_superuser_password: 'user'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.localhost", "https://stag.localhost", "https://localhost", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@abcd.com'
  postgres_password: 'user'
  pgadmin_default_user: 'artiom.blinovas@gmail.com'
  pgadmin_default_user_password: 'user'
  traefik_constraint_tag: 'localhost'
  traefik_constraint_tag_staging: 'stag.localhost'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:user'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
